default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["AIRBNB_CLONE_DATABASE_USERNAME"] %>
  password: <%= ENV["AIRBNB_CLONE_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airbnb_clone_development

test:
  <<: *default
  database: airbnb_clone_test

production:
  <<: *default
  database: airbnb_clone_production
  username: airbnb_clone
  password: <%= ENV["AIRBNB_CLONE_DATABASE_PASSWORD"] %>
